/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8411ab4e-f8c8-42d7-b168-2ca3b4251fff",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZFzVtubYz",
    "aws_user_pools_web_client_id": "7lr08o1k3u8dim8r7k8jhtm12r",
    "oauth": {}
};


export default awsmobile;
