/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:34e871f9-8139-42ec-9778-38971ed4273a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QmPlkTkyi",
    "aws_user_pools_web_client_id": "7552ihptjm82k06g2eaad8q6c1",
    "oauth": {}
};


export default awsmobile;
